name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [ 3.8 ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run Flake8
                run: |
                    pip install flake8
                    flake8 .

            -   name: Run Test
                run: |
                    pip install tox
                    tox -e ${{ matrix.python-version }}

            -   name: Build package
                run: |
                    python setup.py sdist

            -   name: Upload Python package artifact
                uses: actions/upload-artifact@v3
                with:
                    name: dist
                    path: dist/*
