name: Build and Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - master
            - python-workflows-poc

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11
                  cache: 'pip'

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install tox
                    pip install flake8

            -   name: Run Test
                run: tox

            -   name: Lint code
                run: |
                    pip install flake8
                    flake8 .

            -   name: Build package
                run: |
                    python setup.py sdist bdist_wheel

            -   name: Upload Python package artifact
                uses: actions/upload-artifact@v3
                with:
                    name: dist
                    path: dist/*
